name: Lint
run-name: Lint for ${{ github.repository }}

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out ${{ github.ref }} after a ${{ github.event_name }} event
        uses: actions/checkout@v6

      - name: Cache node modules
        uses: actions/setup-node@v6
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint