name: ESLint
run-name: Lint for ${{ github.repository }}

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out ${{ github.ref }} after a ${{ github.event_name }} event
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Cache node modules
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint